/*
FILE: uta/types/trade.go

DESCRIPTION:
Domain types for the V3 UTA order-flow surface: order acks, batch
per-item results, the unified Order view (order-info / unfilled / history)
and execution Fills. Field mapping verified against the Bitget V3 docs
and the tiagosiebler reference types (OrderInfoV3 / UnfilledOrderV3 /
HistoryOrderV3 / FillV3). decimal for prices / sizes, int64 epoch-ms.
*/

package types

import "github.com/shopspring/decimal"

// OrderAck — the minimal ack returned by place / modify / cancel single.
type OrderAck struct {
	OrderID   string
	ClientOID string
}

// BatchOrderResult — one per-item result of a batch place / modify /
// cancel (and of cancel-symbol-order / close-positions). Code / Msg are
// empty on success.
type BatchOrderResult struct {
	OrderID   string
	ClientOID string
	Code      string
	Msg       string
}

// FeeDetail — one fee line on an order or fill.
type FeeDetail struct {
	FeeCoin string
	Fee     decimal.Decimal
}

// Order — unified order view (order-info / unfilled-orders / history, and
// the rows of the private WS `order` topic via uta.StreamClient.WatchOrders).
// Fields absent for a given endpoint / transport stay zero.
//
// WS NOTES:
//   - Category is normalised to the canonical UPPER-CASE form
//     ("USDT-FUTURES") — the WS row ships it lower-case ("usdt-futures"),
//     REST ships it upper-case; consumers compare against the Category
//     constants either way.
//   - PosSide carries the WS `holdSide` (long / short).
//   - OrderStatus is passed through verbatim:
//     new | partially_filled | filled | cancelled.
type Order struct {
	OrderID      string
	ClientOID    string
	Category     string
	Symbol       string
	OrderType    string
	Side         string
	Price        decimal.Decimal
	Qty          decimal.Decimal
	Amount       decimal.Decimal
	CumExecQty   decimal.Decimal
	CumExecValue decimal.Decimal
	AvgPrice     decimal.Decimal
	TimeInForce  string
	OrderStatus  string
	PosSide      string
	HoldMode     string
	DelegateType string
	ReduceOnly   string
	FeeDetail    []FeeDetail
	CancelReason string
	ExecType     string
	StpMode      string
	CreatedTime  int64
	UpdatedTime  int64

	// WS-only fields (zero on REST rows).

	// TradeSide — open / close (and the venue's extended enumerations).
	TradeSide string
	// MarginMode — crossed / isolated.
	MarginMode string
	// MarginCoin — margin coin of the order (e.g. "USDT").
	MarginCoin string
	// Leverage — order leverage.
	Leverage decimal.Decimal
	// TotalProfit — realised profit attributed to the order.
	TotalProfit decimal.Decimal
}

// Fill — one execution row (trade/fills, and the rows of the private WS
// `fill` topic via uta.StreamClient.WatchFills).
//
// WS NOTES:
//   - Category is normalised to the canonical UPPER-CASE form (see Order).
//   - The WS row has no createdTime; CreatedTime falls back to ExecTime so
//     code shared with the REST path keeps a fill timestamp.
type Fill struct {
	ExecID      string
	OrderID     string
	Category    string
	Symbol      string
	OrderType   string
	Side        string
	ExecPrice   decimal.Decimal
	ExecQty     decimal.Decimal
	ExecValue   decimal.Decimal
	TradeScope  string
	FeeDetail   []FeeDetail
	ExecPnl     decimal.Decimal
	TradeSide   string
	CreatedTime int64
	UpdatedTime int64

	// WS-only fields (zero on REST rows).

	// ClientOID — client order id of the filled order.
	ClientOID string
	// ExecTime — execution time generated by the matching engine, epoch-ms.
	ExecTime int64
	// PosSide — position side of the fill (WS `holdSide`: long / short).
	PosSide string
	// IsRPI — the fill is a Retail Price Improvement execution.
	IsRPI bool
	// ExecLinkID — execution correlation id (links both sides of a trade).
	ExecLinkID string
}
